### ISSUE TITLE
error: failed linking file resources.

### ISSUE THREAD

**Issue by EyeMoney** [scwang90/MultiWaveHeader#10]
error: attribute 'com.eye.tree:mwhRunning' not found.
Message{kind=ERROR, text=error: attribute 'com.eye.tree:mwhRunning' not found., sources=[F:\AndroidProject\Tree\NormalJoy\src\main\res\layout\main_activity_frist.xml:27], original message=, tool name=Optional.of(AAPT)}

<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:id="@+id/first_linear_one"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical"
    tools:context="com.eye.tree.entranceMain.FirstActivity">

    <android.support.v7.widget.Toolbar
        android:id="@+id/fri_toolbar"
        android:layout_width="match_parent"
        android:layout_height="?attr/actionBarSize"
        android:background="#009687"
        android:elevation="10dp">
        

        <com.scwang.wave.MultiWaveHeader
            android:id="@+id/fri_waveHeader"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:layout_marginTop="26dp"
            android:scaleY="-1"
            app:mwhCloseColor="@color/colorPrimaryLight"
            app:mwhColorAlpha="0.45"
            app:mwhGradientAngle="45"
            app:mwhProgress="1"
            app:mwhRunning="true"
            app:mwhStartColor="@color/colorPrimaryDark"
            app:mwhVelocity="1"
            app:mwhWaveHeight="50dp"
            app:mwhWaves="MultiWave" />

    </android.support.v7.widget.Toolbar>

    <ScrollView
        android:layout_width="match_parent"
        android:layout_height="match_parent">

        <LinearLayout
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:orientation="vertical">

            <ImageView
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                android:contentDescription="@string/LOADING"
                android:src="@mipmap/query_room_age2" />

        </LinearLayout>
    </ScrollView>

</LinearLayout>

but 
-->
        <com.scwang.wave.MultiWaveHeader
            android:id="@+id/fri_waveHeader"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:layout_marginTop="26dp"
            android:scaleY="-1"
            app:mwhCloseColor="@color/colorPrimaryLight"
            app:mwhColorAlpha="0.45"
            app:mwhGradientAngle="45"
            app:mwhProgress="1"
            app:mwhStartColor="@color/colorPrimaryDark"
            app:mwhVelocity="1"
            app:mwhWaveHeight="50dp"
            app:mwhWaves="MultiWave" />

it works,and is mwhRunning, i do not why,

**Comment by scwang90** [comment]
Delete this line of code
```
app:mwhRunning="true"
```

**Comment by EyeMoney** [comment]
好的，谢谢老哥

**Comment by EyeMoney** [comment]
> This could be the reason for the AndroidStudio build，but you can delete this line of code.
> 
> ```
> app:mwhRunning="true"
> ```
> 
> The default value of mwhRunning is true

好的，谢谢老哥
