### ISSUE TITLE
When height goes greater than 1, the waveheader starts to go out of screen

### ISSUE THREAD

**Issue by root-ansh** [scwang90/MultiWaveHeader#13]
hi. first of all thankyou for this amazing library! made my app ui look even more beautiful.  
Secondly, I have a small problem. I have a button which sets the progress as `waveHeader.setProgress(waveHeader.getProgress()+0.1f)` for some clicks. But in this way, when the progress count becomes greater than 1, theheader goes out of screen. And even when the header is onScreen at progress= exact `1`, the header would not cover the complete screen, the waves would be still shorter than the top edge of the screen. Is there a way to cover the complete screen?

I also wanted to know if we could somehow make the animation of `setProgress()` more smooth, because even a small change from `0.5f` to `0.6f` is very abrupt. 

Thanks again for this awesome library!!!

**Comment by scwang90** [comment]
version `1.0.0-alpha-2`  has published.

you can update to it and call `setEnableFullScreen` and `setProgress(progress, interpolator, duration)` methods.
