### ISSUE TITLE
Is not working in android x, wave is not showing

### ISSUE THREAD

**Issue by sabbir073** [scwang90/MultiWaveHeader#14]
com.scwang.wave:MultiWaveHeader:1.0.0-andx-3 is getting error in build.

not working in android X

Error: failed to resolve com.scwang.wave:MultiWaveHeader:1.0.0-andx-3

**Comment by MycroftWong** [comment]
同样的问题，我把源码弄下来了 @scwang90

**Comment by kilo-swodh** [comment]
same to me

**Comment by vickyKDV** [comment]
same to me, please fix it

**Comment by vickyKDV** [comment]
fixed

**Comment by sabbir073** [comment]
vickyKDV how you fixed it?

**Comment by vickyKDV** [comment]
> vickyKDV how you fixed it?

yes fixed it

**Comment by SaiferGit** [comment]
For me -3 wasn't working.
Instead of I used:  **implementation 'com.scwang.wave:MultiWaveHeader:1.0.0-alpha-1'**

**XML Code for mine:** 
<com.scwang.wave.MultiWaveHeader
            android:id="@+id/waveHeader"
            android:layout_width="match_parent"
            android:layout_height="450dp"
            app:mwhStartColor="@color/Your_Start_Color"
            app:mwhCloseColor="@color/Yor_End_Color"
            app:mwhWaves="MultiWave">

        </com.scwang.wave.MultiWaveHeader>
**Java Code for mine:**
        Multiheader waveHeader = findViewById(R.id.waveHeader);

        waveHeader.setColorAlpha(.5f);
        waveHeader.setVelocity(5f);
        waveHeader.setProgress(1f);
        waveHeader.isRunning();
        waveHeader.setGradientAngle(45);
        waveHeader.setWaveHeight(50);

**Comment by BharathKSunil** [comment]
Guys: 
```
implementation 'com.github.BharathKSunil:MultiWaveHeader:v1.0.0-alpha-4'
```

**Comment by BharathKSunil** [comment]
I have updated a few things and made a release:
```
implementation 'com.github.BharathKSunil:MultiWaveHeader:v1.0.0-alpha-4'
```
UPDATES:
- Moved it to kotlin. 
- Small Improvements: #19 
- Also replace `app:mwhRunning="true"` to `app:mwhIsRunning="true"`

Created an issue #20 to make a release and update readme for the author

**Comment by scwang90** [comment]
1.0.0 
1.0.0-andx 
正式版已经发布

**Comment by Stephan-Robert** [comment]
Class reference not found. I copied @BharathKSunil 's implementation. And any other implementation, like alpha -1, -4, andx, all of the above. Nothing seems to work. Are there any settings you have to set in Android Studio that I don't know of?

error:
Class referenced in the layout file, com.scwang.wave.MultiWaveHeader, was not found in the project or the libraries
Cannot resolve class com.scwang.wave.MultiWaveHeader

**Comment by asadwaheed1** [comment]
JCenter is shutdown. is this library available on any other repo?
