### ISSUE TITLE
导入失败

### ISSUE THREAD

**Issue by ilatent** [scwang90/MultiWaveHeader#16]
ERROR: Failed to resolve: com.scwang.wave:MultiWaveHeader:1.0.0-alpha-3
Show in Project Structure dialog
Affected Modules: app

**Comment by longer96** [comment]
+1

**Comment by returntoorigin** [comment]
> +1

代码不是太多，我是直接把代码copy到项目中去了，我怀疑是这个项目已经被删除了，无法使用远程引用该库

**Comment by longer96** [comment]
3q

**Comment by kilo-swodh** [comment]
+1

**Comment by scwang90** [comment]
1.0.0 1.0.0-andx 正式版已经发布
