### ISSUE TITLE
仓库无效问题

### ISSUE THREAD

**Issue by LvanCham** [scwang90/MultiWaveHeader#17]
implementation 'com.scwang.wave:MultiWaveHeader:1.0.0-alpha-3'

    //androidx
    implementation 'com.scwang.wave:MultiWaveHeader:1.0.0-andx-3'

都没有
 implementation 'com.scwang.wave:MultiWaveHeader:1.0.0-alpha-1' 无奈用回这个

**Comment by scwang90** [comment]
1.0.0 
1.0.0-andx 
正式版已经发布
