### ISSUE TITLE
Corrections

### ISSUE THREAD

**Issue by shadsluiter** [scwang90/MultiWaveHeader#8]
Change the code for the most current version of Android Studio...

Dependency

    implementation 'com.scwang.wave:MultiWaveHeader:1.0.0-alpha-1'

Layout XML is missing the close tag.

    <com.scwang.wave.MultiWaveHeader
        android:id="@+id/waveHeader"
        android:layout_width="match_parent"
        android:layout_height="200dp">

    </com.scwang.wave.MultiWaveHeader>

**Comment by scwang90** [comment]
thanks
